metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

# idk why rcp_ is needed without replication but ok 
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "192.168.1.43:3901"
rpc_secret = "c183b95e884c59e8cb581a0686f823307faf533f702d6d0fb27ad20ca259601b"

compression_level = 2

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"

[s3_web]
bind_addr = "[::]:3902"
root_domain = "localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "$(openssl rand -base64 32)"
metrics_token = "$(openssl rand -base64 32)"
